Add files via upload
Dashundel/C-Lessons pull request #1
Opened 2023-05-19 13:54 UTC by Dashundel

Добавлено ДЗ по 5 и 6 уроку, задание из 6 урока. Внесены правки по замечаниям

2023-05-31 14:55 UTC, temicch requested changes

2023-05-31 14:55 UTC, temicch commented on HW456/Client.cs
> +public class Client
Забегу вперед: если класс не предполагает инстанцирование от него, а имеет только общую структуру, то стоит сделать его Абстрактным (или, в большинстве случаев, выделить интерфейс. Но в данном случае можно абстрактный класс использовать)

2023-05-31 14:55 UTC, temicch commented on HW456/Client.cs
> +    public static void func()
> Реализовать метод, который возвращает отформатированное название и сумму заказа

Данный метод делает явно больше необходимого (инстанцирование двух дочерних классов).

Вообще не очень хорошо, что родительский класс знает что то о дочерних (если только не через какой то интерфейс взаимодействия, и то надо думать). В данном случае я бы такую функцию вынес либо в `Extension Method`, либо в какое то постороннее место (да даже в `Main.cs`)

2023-05-31 14:55 UTC, temicch commented on HW456/Client.cs
> +        ieClient.name = "Блабла Бла Бла";
Можно же в одну инструкцию обойтись:
```suggestion
        IE ieClient = new IE
        {
            id = 65482631,
            phone = "+7(499)568945",
            orderSum = 512,
            date = DateOnly.FromDateTime(DateTime.Now.AddYears(-30)),
            name = "Блабла Бла Бла",
        };

```
И ниже так же

2023-05-31 14:55 UTC, temicch commented on HW456/Client.cs
> +    public int orderSum;
Публичные переменные с большой буквы
```suggestion
    public int Id;
    public string Phone;
    public int OrderSum;

```
[Гайдлайн на MSDN](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines) (обычно IDE подсвечивает такие моменты).

Поправь и в остальных местах

2023-05-31 14:55 UTC, temicch commented on HW456/Client.cs
> +public class IE: Client
Название классов не очень хорошее выбрано

2023-05-31 14:55 UTC, temicch commented on HW456/HW56/Accounts/IncreaseAccount.cs
> +public class IncreaseAccount
Что значит `IncreaseAccount`? Это же Банковский счет, можно было бы `BankAccount`.

И стоит сделать класс Абстрактным, если данный класс не предполагает инстанцирование

2023-05-31 14:55 UTC, temicch commented on HW456/HW56/Accounts/IncreaseAccount.cs
> +        }
Вообще тут else лишний, т.к. первое условие прерывает дальнейшее выполнение.

И тут стоит изменить немного код: обычно, если есть какой то негативный сценарий, который прерывает дальнейшее выполнение кода, то его переносят в самое начало метода, так вложенность последующего сценария понижается.
Имею ввиду сделать так:

```suggestion
        if (!IsActive)
        {
            Console.WriteLine("Operation is not available");
            return false;
        }

        Balance += sum;
        return true;
```

2023-05-31 14:55 UTC, temicch commented on HW456/HW56/Accounts/IncreaseAccount.cs
> +    }
Здесь так же можно понизить вложенность:
```suggestion
    public virtual void DecreaseBalance(decimal sum)
    {
        if (!IsActive)
        {
            Console.WriteLine("Operation is not available");
            return;
        }

        if (sum > Balance)
        {
            Console.WriteLine("The amount of decreasing is bigger then the balance");
            return;
        }

        Balance -= sum;
    }
```

2023-05-31 14:55 UTC, temicch commented on HW456/HW56/Accounts/IncreaseAccount.cs
> +    }
Там и ниже есть места, где тоже можно так сделать

2023-05-31 14:55 UTC, temicch commented on HW456/HW56/Accounts/IncreaseAccount.cs
> +    public virtual void DecreaseBalance(decimal sum)
`IncreaseBalance` возвращает `true` в случае успешной операции, может тут стоит сделать так же?

2023-06-09 12:00 UTC, Dashundel commented on HW456/Client.cs
> +public class Client
поправила

2023-06-09 12:05 UTC, Dashundel commented on HW456/Client.cs
> +        ieClient.name = "Блабла Бла Бла";
поправила

2023-06-09 12:06 UTC, Dashundel commented on HW456/Client.cs
> +    public int orderSum;
поправила

2023-06-09 12:08 UTC, Dashundel commented on HW456/HW56/Accounts/IncreaseAccount.cs
> +public class IncreaseAccount
поправила

2023-06-09 12:10 UTC, Dashundel commented on HW456/HW56/Accounts/IncreaseAccount.cs
> +        }
поправила

2023-06-09 12:12 UTC, Dashundel commented on HW456/HW56/Accounts/IncreaseAccount.cs
> +    }
попраивла

2023-06-09 12:15 UTC, Dashundel commented on HW456/HW56/Accounts/IncreaseAccount.cs
> +    public virtual void DecreaseBalance(decimal sum)
поправила

2023-06-09 12:43 UTC, Dashundel commented on HW456/Client.cs
> +    public static void func()
перенесла в маин

2023-06-09 12:43 UTC, Dashundel commented on HW456/Client.cs
> +public class IE: Client
переименовала

2023-08-01 05:51 UTC, merged