Add files via upload
Dashundel/C-Lessons pull request #3
Opened 2023-05-26 05:03 UTC by Dashundel

+ ДЗ 6,7, внесены изменения в ДЗ 5,. + задание из лекции 6,7

2023-05-31 14:56 UTC, temicch requested changes

2023-05-31 14:56 UTC, temicch commented on HW456/ClassesHW56/Accounts/IncreaseAccount.cs
> +            return false;
Стоит выработать единый подход к обработке негативных сценариев. Либо в обоих случаях кидай исключение, либо пиши в консоль проблему.

Лучше кинуть исключение - а дальнейшую обработку пусть берет на себя вызывающий код.

И если решишь поменять на исключение - то стоит сделать это и в остальных классах

2023-05-31 14:56 UTC, temicch commented on HW456/ClassesHW56/Accounts/MetalAccount.cs
> +        base.DecreaseBalance(amount);
Я выше писал об этом, и тут как раз это будет полезно - надо для `DecreaseBalance` сделать либо возврат `false` если операция не удалась и проверять ниже, либо кидать в родительском методе исключение

2023-05-31 14:56 UTC, temicch commented on HW456/ClassesHW56/Clients/BankClient.cs
> +    public decimal TotalBalace
```suggestion
    public decimal TotalBalance

```

2023-05-31 14:56 UTC, temicch commented on HW456/ClassesHW56/Clients/BankClient.cs
> +    public decimal TotalBalace
Можно заменить на такую запись (читается легче):
`
    public decimal TotalBalance => Accounts.Sum(x => x.Balance);
`

2023-05-31 14:56 UTC, temicch commented on HW456/ClassesHW56/Bank.cs
> +    }
Метод приватный и нигде не может использоваться.

И не похоже на транзакцию - она не откатывает изменения на втором счете, если с первого не удалось снять средства, надо такое обработать

2023-05-31 14:56 UTC, temicch commented on HW456/ClassesHW56/Clients/BankClient.cs
> +        BankClient bankClient = (BankClient)obj!;
Обычно IDE [может сгенерировать](https://www.jetbrains.com/help/rider/Code_Generation_Relational_Members.html) компаратор, который и стоило бы здесь заиспользовать, например:
```
    public int CompareTo(object? obj)
    {
        if (ReferenceEquals(null, obj)) return 1;
        if (ReferenceEquals(this, obj)) return 0;

        return obj is Client other
            ? TotalBalance.CompareTo(other.TotalBalance)
            : throw new ArgumentException($"Object must be of type {nameof(Client)}");
    }
```

2023-05-31 14:56 UTC, temicch commented on HW456/ClassesHW56/Clients/BankClient.cs
> +    protected int AccountsCount { get; set; }
На самом деле это скорее `AccountsLimit`. И возможно стоило бы его сделать `readonly`, т.к. по ходу приложения это значение не должно меняться

2023-05-31 14:56 UTC, temicch commented on HW456/ClassesHW56/Clients/BankClient.cs
> +        Accounts = new List<IncreaseAccount>();
Тут можно смело количество счетов прокинуть в конструктор

2023-05-31 14:56 UTC, temicch commented on HW456/ClassesHW56/Clients/BankClient.cs
> +        catch (InvalidDataException) when(Accounts.Count > AccountsCount)
Откуда тут `InvalidDataException`?

Я бы сделал обработку `Accounts.Count >= AccountsCount` в самом начале метода и кидал бы исключение, а вызывающий код пусть сам разбирается что делать, не надо тут в консоль писать

2023-05-31 14:56 UTC, temicch commented on HW456/ClassesHW56/Clients/BankClient.cs
> +        for (int i = 0; i < Accounts.Count; i++)
Возможно стоит добавить обработку `Accounts.Count>=accountNumber>=0` и кидать `ArgumentOutOfRangeException` если передали что то не то

2023-05-31 14:56 UTC, temicch commented on HW456/ClassesHW56/Clients/BankClient.cs
> +                Accounts.RemoveAt(i);
Счет из списка удалили, но сам счет не закрыт.

Вообще формулировка задачи предполагает, что счет будет просто закрыт, вероятно удалять его из списка не надо

2023-05-31 14:56 UTC, temicch commented on HW456/ClassesHW56/Clients/TypeClient.cs
> +class SimpleBankClient : BankClient
Давай здесь и в остальных файлах приберемся - один файл на класс

2023-05-31 14:56 UTC, temicch commented on HW456/ClassesHW56/Clients/TypeClient.cs
> +        AccountsCount = 10;
На самом деле, может и не стоит это поле хранить в родительском классе? Не его это обязанность. Стоило бы такое поле передвинуть и сделать приватным (или `protected`, на твой вкус) в обоих дочерних классах, и переопределить метод добавления счета, где будет проверка на количество счетов.

Вдруг будет тип клиента с неограниченным количеством счетов?

2023-06-09 06:44 UTC, Dashundel commented on HW456/ClassesHW56/Accounts/IncreaseAccount.cs
> +            return false;
поменяла на исключение

2023-06-09 06:45 UTC, Dashundel commented on HW456/ClassesHW56/Accounts/MetalAccount.cs
> +        base.DecreaseBalance(amount);
поменяла на исключение в родительском

2023-06-09 07:19 UTC, Dashundel commented on HW456/ClassesHW56/Clients/BankClient.cs
> +    public decimal TotalBalace
поменяла

2023-06-16 14:17 UTC, Dashundel commented on HW456/ClassesHW56/Clients/BankClient.cs
> +        catch (InvalidDataException) when(Accounts.Count > AccountsCount)
переелала

2023-06-16 14:17 UTC, Dashundel commented on HW456/ClassesHW56/Clients/BankClient.cs
> +        for (int i = 0; i < Accounts.Count; i++)
добавила

2023-06-16 14:17 UTC, Dashundel commented on HW456/ClassesHW56/Clients/BankClient.cs
> +                Accounts.RemoveAt(i);
поправила

2023-06-16 14:17 UTC, Dashundel commented on HW456/ClassesHW56/Clients/BankClient.cs
> +        BankClient bankClient = (BankClient)obj!;
спасибо,поправила

2023-06-16 14:17 UTC, Dashundel commented on HW456/ClassesHW56/Clients/TypeClient.cs
> +class SimpleBankClient : BankClient
поправила

2023-06-16 14:17 UTC, Dashundel commented on HW456/ClassesHW56/Bank.cs
> +    }
поправила

2023-06-16 14:17 UTC, Dashundel commented on HW456/ClassesHW56/Clients/BankClient.cs
> +    protected int AccountsCount { get; set; }
название поменяла, а на readonly rider поругался, сказал, что так нельзя

2023-06-16 14:17 UTC, Dashundel commented on HW456/ClassesHW56/Bank.cs
> +    }
поменяла

2023-06-16 14:17 UTC, Dashundel commented on HW456/ClassesHW56/Clients/BankClient.cs
> +    protected int AccountsCount { get; set; }
переименовала, но на readonly rider ругнулся

2023-06-16 14:17 UTC, Dashundel commented on HW456/ClassesHW56/Clients/TypeClient.cs
> +        AccountsCount = 10;
поправила

2023-06-25 18:11 UTC, temicch requested changes

2023-06-25 18:11 UTC, temicch commented on ClassesHW56/Accounts/BankAccount.cs
> +    }
Минор: порядок проверок тут плавает, может лучше к одному порядку привести? Имею ввиду, что в первом методе проверяется сначала аргумент, а затем активность счета. Во втором методе сейчас последовательность прямо противоположная. Можно проверять сначала аргументы, а затем активность счета в обоих методах.

И по поводу возвращаемого значения метода - сейчас эти методы не возвращают `false` в родительском классе. В имплементациях метод то возвращает `false`, то выкидывает исключения.

Тут грань между исключением и выдаваемым значением размыта - надо дать пользователю обратную связь по поводу попытки изменения баланса. Если `false` вернуть - а как понять почему операция не удалась? Лучше тогда возвращать одно из:
* Каждый метод возвращает структуру, которая либо `Ok`, либо `Fail` с понятным сообщением
* Метод выкидывает исключение с понятным сообщением

Первый пункт избыточен для задачи, можно использовать второй пункт. Но смысл такой - надо дать обратную связь по неудачной операции. И раз переход будет на исключения - следует убрать возвращаемое значение у методов, пусть будет `void`

2023-06-25 18:11 UTC, temicch commented on ClassesHW56/Accounts/BankAccount.cs
> +    }
Условие задачи:

> Счет не может быть закрыт, если он имеет положительный баланс.

Тут это условие не соблюдено (проверка не та)

2023-06-25 18:11 UTC, temicch commented on ClassesHW56/Accounts/MetalAccount.cs
> +    }
```suggestion
    public override decimal Balance => MetalPrice * MetalWeight;
```

2023-06-25 18:11 UTC, temicch commented on ClassesHW56/Accounts/MetalAccount.cs
> +        }
`else` не нужен, если по коду выше возвращается управление через `return`

2023-06-25 18:11 UTC, temicch commented on ClassesHW56/Accounts/SavingAccount.cs
> +        DecreaseBalance(amount);
Тут метод сам себя вызывает, бесконечная рекурсия

2023-06-25 18:11 UTC, temicch commented on ClassesHW56/Accounts/SavingAccount.cs
> +        }
Сначала проверка, затем логика. Так уменьшается вложенность кода, да и чище смотрится:
```suggestion
        if (amount < InitialDeposit)
        {
            throw new ArgumentOutOfRangeException("amount", "The amount is bigger than initial deposit");
        }

        base.DecreaseBalance(amount);

        return true;
```

И `true` здесь возвращать несправедливо по отношению к `base.DecreaseBalance(amount);`, ведь он может и `false` вернуть. В общем, надо возвращать его:
```c#
return base.DecreaseBalance(amount);
```

2023-06-25 18:11 UTC, temicch commented on ClassesHW56/Accounts/SavingAccount.cs
> +        }
То же самое, что и у метода выше. Сначала проверка, потом логика

2023-06-25 18:11 UTC, temicch commented on ClassesHW56/Clients/BankClient.cs
> +        }
Сначала проверка, затем логика. И называть аккаунт переменной `i` не особо правильно, этот итератор вполне именуем:
```suggestion
        if (Accounts.Count < Convert.ToInt32(accountNumber) || Convert.ToInt32(accountNumber) < 0)
        {
            throw new ArgumentException("Bad accountNumber");
        }

        foreach (var account in Accounts)
        {
            if (account.AccountNumber == accountNumber)
            {
                CloseAccount(account.AccountNumber);
            }
        }
```

2023-06-25 18:11 UTC, temicch commented on ClassesHW56/Clients/BankClient.cs
> +            : throw new ArgumentException($"Object must be of type {nameof(Client)}");
Я запутался в разных ДЗ, но кажется тут должен быть `BankClient`

2023-06-25 18:11 UTC, temicch commented on ClassesHW56/Clients/BankClient.cs
> +public class BankClient: IComparable
Объекты данного класса должны быть созданы? Если нет - стоит сделать класс абстрактным

2023-06-25 18:11 UTC, temicch commented on ClassesHW56/Clients/SimpleBankClient.cs
> +         }
`else` не нужен, так как в проверке ранее возвращается управление посредством `throw`

2023-06-25 18:11 UTC, temicch commented on ClassesHW56/Clients/VipBankClient.cs
> +        }
Такая же ситуация с `else`, как и в `SimpleBankClient`

2023-06-25 18:11 UTC, temicch commented on Client.cs
> +    public int OrderSum;
`decimal` по аналогии с `TotalBalance`

2023-06-25 18:11 UTC, temicch commented on Client.cs
> +    }
```suggestion
    public virtual string Info => Id + '\n' + Phone + '\n' + OrderSum.ToString() + "руб";
```

2023-06-25 18:11 UTC, temicch commented on Main.cs
> +        };
Обычно используется `var` для уменьшения кода. И скобки можно опускать когда класс инстациируется с указанием полей:
```suggestion        
        var individualEntrepreneurClient = new IndividualEntrepreneur
        {
            Id = 65482631,
            Phone = "+7(499)568945",
            OrderSum = 512,
            Date = DateOnly.FromDateTime(DateTime.Now.AddYears(-30)),
            Name = "Блабла Бла Бла",
        };
```

2023-06-25 18:11 UTC, temicch commented on SimpleFractionStructure.cs
> +    public int Denominator { get; private set; }
Сеттеры лучше задать `init`, так они точно не будут изменены вне конструктора

2023-06-25 18:11 UTC, temicch commented on SimpleFractionStructure.cs
> +    }
Почему методы статические?

2023-06-25 18:11 UTC, temicch commented on HW7.cs
> +            compare[i] = new SimpleFractionStructure(rand.Next(10), rand.Next(15));
`rand.Next()` может ноль вернуть, это критично для знаменателя:
```suggestion
            compare[i] = new SimpleFractionStructure(rand.Next(10), 1 + rand.Next(15));
```

2023-06-25 18:16 UTC, temicch commented on HW456/ClassesHW56/Clients/BankClient.cs
> +    protected int AccountsCount { get; set; }
Тут уже я был не прав: `protected List<BankAccount> Accounts { get; }` уже подразумевает, что свойство по сути `readonly`

2023-08-01 05:56 UTC, merged

2023-08-01 06:02 UTC, Dashundel commented on HW7.cs
> +            compare[i] = new SimpleFractionStructure(rand.Next(10), rand.Next(15));
поправила

2023-08-01 06:04 UTC, Dashundel commented on SimpleFractionStructure.cs
> +    public int Denominator { get; private set; }
поправла

2023-08-01 06:04 UTC, Dashundel commented on SimpleFractionStructure.cs
> +    }
поправила

2023-08-01 06:10 UTC, Dashundel commented on SimpleFractionStructure.cs
> +    public int Denominator { get; private set; }
поправила

2023-08-01 06:12 UTC, Dashundel commented on Main.cs
> +        };
поправила

2023-08-01 06:13 UTC, Dashundel commented on Client.cs
> +    }
поправила

2023-08-01 06:15 UTC, Dashundel commented on Client.cs
> +    public int OrderSum;
поправила

2023-08-01 06:16 UTC, Dashundel commented on ClassesHW56/Clients/SimpleBankClient.cs
> +         }
поправила

2023-08-01 06:19 UTC, Dashundel commented on ClassesHW56/Clients/BankClient.cs
> +public class BankClient: IComparable
поправила

2023-08-01 06:29 UTC, Dashundel commented on ClassesHW56/Clients/BankClient.cs
> +            : throw new ArgumentException($"Object must be of type {nameof(Client)}");
тут все правильно

2023-08-01 06:31 UTC, Dashundel commented on ClassesHW56/Clients/BankClient.cs
> +        }
поправила

2023-08-01 06:33 UTC, Dashundel commented on ClassesHW56/Accounts/SavingAccount.cs
> +        }
поправила

2023-08-01 06:34 UTC, Dashundel commented on ClassesHW56/Accounts/SavingAccount.cs
> +        }
поправила